### ISSUE TITLE
red / blue dots lines not related to Safecast on the Tilemap explained

### ISSUE THREAD

**Issue by Lugulbanda** [Safecast/Tilemap#7]
i noticed that on some locations, on the tile map, markings appear, it looks like the safecast Satellite Map, (wich is not very up to date), gets some addons, in case of the marked parks in America, 
u see the red from very far away,

 from were do we get the map data? is it editable?, or do we share it with other companys?... (iknowgoogle)

i have no problem with people mark and edit stuff on the sattlite map, but using red and blue colors we use for safecast, can lead to a problem into the future, if someone thinks a park is dangerous cuz ist circled around and radiate in Red Color.. or if some streets ans pass ways come into dark blue and should be colored differnt.

i attached some spots on the tile sattelite map

![safecast1](https://user-images.githubusercontent.com/33792744/33796973-7268a460-dcff-11e7-9289-2dbd24befe59.JPG)

![safecast4](https://user-images.githubusercontent.com/33792744/33796975-7297367c-dcff-11e7-9b7b-0f51dc10f410.JPG)
![safecast5](https://user-images.githubusercontent.com/33792744/33796976-72ae1b62-dcff-11e7-9584-50d6e9e30f94.JPG)
![safecast6](https://user-images.githubusercontent.com/33792744/33796977-72c5cbd6-dcff-11e7-921d-b30eb557a4fd.JPG)

![savecast0](https://user-images.githubusercontent.com/33792744/33796979-72f35b78-dcff-11e7-8029-5fab18895a1c.JPG)

#

**Comment by Lugulbanda** [comment]
ok i saw some of this USA Area fields in the tile map options, u can shut down, but what are they displaying, woodfires ? greek lilac skirball thoumas fire?, and i disscovered a bug if i want to shut down lilac, the greek fire button is moving.. not the lilac... i sugest a on mouse over option to see what that is about, and why its so special that u can turn it on and of ...

**Comment by Lugulbanda** [comment]
the options link under bgeige logs is also not working...

**Comment by Azby** [comment]
Thanks for looking closely. 
-- As you note, we have included outlines for the Fukushima evacuation zone as well as fire zones in Southern California. As you discovered, display of all of these can be toggled on and off. The other colored lines in the map screenshots you posted are ski slopes which are part of the underlying basemaps themselves. If you find them confusing or distracting, please note that it is possible to select from 13 basemaps, as well as plain white or black backgrounds. 
-- The "Options" control for bGeigie logs is only operational when a log file has been loaded and diaplayed. I agree this might not be clear.
 
The Safecast tilemap is constantly being improved and new features added, mainly thanks to Nick Dolezal. There was a major upgrade unveiled in Sept 2016, and we posted a blog then describing the features and controls. It's worth reading:  https://blog.safecast.org/2016/09/safecast-web-map-update/

**Comment by Lugulbanda** [comment]
hello,

thx for the link and time for explain :)

best wishes

 

 

Gesendet: Sonntag, 10. Dezember 2017 um 05:18 Uhr
Von: Azby <notifications@github.com>
An: Safecast/Tilemap <Tilemap@noreply.github.com>
Cc: Lugulbanda <Starlord@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [Safecast/Tilemap] Invasion of red / blue dots lines not related to Safecast on the Tilemap (#7)


Thanks for looking closely.
-- As you note, we have included outlines for the Fukushima evacuation zone as well as fire zones in Southern California. As you discovered, display of all of these can be toggled on and off. The other colored lines in the map screenshots you posted are ski slopes which are part of the underlying basemaps themselves. If you find them confusing or distracting, please note that it is possible to select from 13 basemaps, as well as plain white or black backgrounds.
-- The "Options" control for bGeigie logs is only operational when a log file has been loaded and diaplayed. I agree this might not be clear.

The Safecast tilemap is constantly being improved and new features added, mainly thanks to Nick Dolezal. There was a major upgrade unveiled in Sept 2016, and we posted a blog then describing the features and controls. It's worth reading: https://blog.safecast.org/2016/09/safecast-web-map-update/
